### ISSUE TITLE
[bug] callback回调两次的问题

### ISSUE THREAD

**Issue by wvq** [tencentyun/cos-wx-sdk-v5#100]
https://github.com/tencentyun/cos-wx-sdk-v5/blob/e260d89fe8ffae1edb40fd12f6afc1cebbe6363e/src/advance.js#L936-L941

这里catch的部分
callback后是不是该return.
或者 catch不做逻辑处理，继续走上传流程.

目前这逻辑，可能先收到一条失败的callback，然后再收到一条成功callback

**Comment by livehigh** [comment]
感谢反馈 我们下个版本修复这里

**Comment by livehigh** [comment]
fixed in v1.6.1
