### ISSUE TITLE
postObject不能自定义headers

### ISSUE THREAD

**Issue by lwpassvoice** [tencentyun/cos-wx-sdk-v5#13]
代码如下：

```
        cos.postObject({
          Bucket: cosConfig.Bucket,
          Region: cosConfig.Region,
          Key: path + name,
          FilePath: tmpPath,
          'x-cos-meta-sskey': sskey,
          'x-cos-meta-token': token,
          'x-cos-meta-tagid': 2,
          TaskReady: (taskId) => {
            console.log('t id', taskId);
          },
          onProgress: (info) => {
            console.log(JSON.stringify(info));
          },
        })
```

小程序调试报了错：
![image](https://user-images.githubusercontent.com/22510735/39793266-46848dac-5377-11e8-9dad-82ced27fbf4f.png)

scf无服务器云函数里也没有自定义的headers:
![image](https://user-images.githubusercontent.com/22510735/39796599-fae64bd4-5389-11e8-9d69-5faf1804b3ce.png)

**Comment by carsonxu** [comment]
谢谢反馈，已修复

**Comment by lwpassvoice** [comment]
![image](https://user-images.githubusercontent.com/22510735/39873987-0f3289fc-549f-11e8-9bf4-a0a0b0ecd8aa.png)
请问下headers里面还是没有自定义的header呢

@carsonxu

**Comment by lwpassvoice** [comment]
@carsonxu
