### ISSUE TITLE
cos.postObject 回调不知道是谁

### ISSUE THREAD

**Issue by wengxianxun** [tencentyun/cos-wx-sdk-v5#15]
我同时上传10个图片， cos.postObject 回调并没告诉我是哪张图片完成

**Comment by wengxianxun** [comment]
for(var i=0; i<res.tempFilePaths.length; i++){
        var filePath = res.tempFilePaths[i]
        var timestamp = Date.parse(new Date());
        timestamp = timestamp;
        var Key = timestamp + that.data.userid+i + '.png'; // 时间戳+用户id+i： 保证图片名称唯一性
        console.log('文件名' + Key);
        cos.postObject({
          Bucket: config.Bucket,
          Region: config.Region,
          Key: Key,
          FilePath: filePath,
          onProgress: function (info) {
            console.log(JSON.stringify(info));
          }
        }, function (err, data) {
          
          that.actionUploadAlbumCallBack(err,data,Key);
        });
      }

比如这段上传代码， 因为回调是异步的，如果有三张图片上传，那成功后那个Key三个都是最后一张图片的名称

**Comment by wengxianxun** [comment]
建议在回调的data里面带回上传的Key参数

**Comment by carsonxu** [comment]
不考虑在返回值加上 Key，你可以加一个闭包来维护对应关系：
```
res.tempFilePaths.forEach(function (filePath) {
	var timestamp = Date.parse(new Date());
	timestamp = timestamp;
	var Key = timestamp + that.data.userid + i + '.png'; // 时间戳+用户id+i： 保证图片名称唯一性
	console.log('文件名' + Key);
	cos.postObject({
		Bucket: config.Bucket,
		Region: config.Region,
		Key: Key,
		FilePath: filePath,
		onProgress: function(info) {
			console.log(JSON.stringify(info));
		}
	}, function(err, data) {
		that.actionUploadAlbumCallBack(err, data, Key);
	});
});
```

**Comment by wengxianxun** [comment]
好的，谢谢

**Comment by wengxianxun** [comment]
res.tempFilePaths.forEach(function (filePath) {
          var timestamp = Date.parse(new Date());
          timestamp = timestamp;
          var Key = timestamp + that.data.userid + i + '.png'; // 时间戳+用户id+i： 保证图片名称唯一性
          console.log('文件名' + Key);
          cos.postObject({
            Bucket: config.Bucket,
            Region: config.Region,
            Key: Key,
            FilePath: filePath,
            onProgress: function (info) {
              console.log(JSON.stringify(info));
            }
          }, function (err, data) {
            console.log('图片名称:'+Key);
            that.actionUploadAlbumCallBack(err, data, Key);
          });
        });

![7ccc2863-8fb1-425e-9272-2dfaf8c7f97b](https://user-images.githubusercontent.com/831898/40785393-fc16847c-651a-11e8-9035-3c42db220467.png)

我上传三张图片，但是回调了好多次，看图

**Comment by carsonxu** [comment]
去掉你外面的 for：
```
for (var i = 0; i < res.tempFilePaths.length; i++) {
}
```
