### ISSUE TITLE
getObject回调 data.Body undefined

### ISSUE THREAD

**Issue by BoatLake** [tencentyun/cos-wx-sdk-v5#17]
（不好意思，上次Issues写错位置了）
我用的就是v5版本，getObject回调data.Body undefined，cos-wx-sdk-v5更换为其他来源的后就没问题。
烦请你看看

**Comment by carsonxu** [comment]
具体点说明怎么复现？我这边正常

**Comment by BoatLake** [comment]
https://github.com/BoatLake/bug-.git
这个，你看看

**Comment by BoatLake** [comment]
我在描述下吧，
先在页面加
var demoSdk = require('../../demo-sdk')
然后在onLoad里
demoSdk.getObject()
demo-sdk.js的回调里加上打印data, console.log(data)
就是没有Body
请求的是txt文件

**Comment by BoatLake** [comment]
我找到问题所在，问题在于小程序的默认配置文件project.config.json setting es6的值为true,
这个文件默认生成，没在意它，es6值改为false后正常，一把辛酸泪啊~~~
建议你在说明中说下相关project.config.json的配置

**Comment by carsonxu** [comment]
感谢反馈！我确认下这个 es6 哪里有问题，尽量做好兼容。
