### ISSUE TITLE
putObject Body内 同时有双引号和中文时 会 403 (Forbidden)

### ISSUE THREAD

**Issue by BoatLake** [tencentyun/cos-wx-sdk-v5#18]
putObject Body内 同时有双引号和中文时 会 403 (Forbidden)
举个简单的例子
cos.putObject({
      Bucket: config.Bucket,
      Region: config.Region,
      Key: fileName,
      Body: ‘中“文’ 
    }, requestCallback);
![image](https://user-images.githubusercontent.com/33485493/44857851-3e51e000-aca3-11e8-9a30-cabbce16f6f2.png)

**Comment by carsonxu** [comment]
已修复
