### ISSUE TITLE
使用方法一和方法二签名算法可以，但是请求存储提示403

### ISSUE THREAD

**Issue by gwbjx123** [tencentyun/cos-wx-sdk-v5#19]
![image](https://user-images.githubusercontent.com/16699142/45586782-c2a49400-b92e-11e8-9b06-74f0640caf02.png)

**Comment by gwbjx123** [comment]
后端为PHP

**Comment by carsonxu** [comment]
做什么操作，申请的临时密钥policy是否有对应权限？

**Comment by gwbjx123** [comment]
我在做一个小程序上传照片到腾讯云存储，使用方法三前端鉴权，可以上传成功，但是用方法一和二的时候，提示403错误

**Comment by gwbjx123** [comment]
我在做一个小程序上传照片到腾讯云存储，使用方法三前端鉴权，可以上传成功，但是用方法一和二的时候，提示403错误

**Comment by gwbjx123** [comment]
我在做一个小程序上传照片到腾讯云存储，使用方法三前端鉴权，可以上传成功，但是用方法一和二的时候，提示403错误

**Comment by carsonxu** [comment]
提供下RequestId，或者可以提交工单解决。

**Comment by gwbjx123** [comment]
NWI5ZDEyNTVfYzI4NWQ2NF8xYjVmMl82OTMyMTU=

**Comment by soqt** [comment]
同样有问题，但是是上传成功，deleteObject的时候出现403错误，"SignatureDoesNotMatch"

**Comment by soqt** [comment]
> 同样有问题，但是是上传成功，deleteObject的时候出现403错误，"SignatureDoesNotMatch"

方法一可以用，但是方法二有问题

**Comment by carsonxu** [comment]
@MojyFantasy 这个报错是因为临时密钥过期，或者 SecretId 写错

**Comment by 7023** [comment]
上述问题解决了吗？同样遇到这个问题，试了很多办法返回总是报403错误

**Comment by carsonxu** [comment]
@7023 解决了吗？如果还有错误可以把完整错误信息贴上。包括 Message、RequestId
