### ISSUE TITLE
使用sdk删除图片

### ISSUE THREAD

**Issue by zhangkaicheng521** [tencentyun/cos-wx-sdk-v5#21]
报文 preview 报

访问拒绝是怎么回事？

deleteObject: function (filePath,cb) {
    var Key = filePath.substr(filePath.lastIndexOf('/') + 1);
    console.log(Key);
    cos.deleteObject({
      Bucket: config.Bucket,
      Region: config.Region,
      Key: Key
    }, function (err, data) {
      if (data) {
        wx.showToast({
          title: '成功',
          icon: 'success',
          duration: 3000
        });
        cb(data)
      }
    });

**Comment by carsonxu** [comment]
解决了没？访问拒绝应该是权限没对
