### ISSUE TITLE
可以上传base64的图片吗

### ISSUE THREAD

**Issue by xiaojia21190** [tencentyun/cos-wx-sdk-v5#24]

**Comment by carsonxu** [comment]
可以试试把 base64 转成 二进制字符串，通过 cos.putObject 接口上传

**Comment by xiaojia21190** [comment]
之前用的是，blob 文件，但是小程序貌似不支持。

**Comment by carsonxu** [comment]
试过base64转了二级制，上传上去图片不正常

**Comment by carsonxu** [comment]
可以考虑通过自己的服务转传。
或者看看 canvas 是否有办法转换（会失真）。

**Comment by xiaojia21190** [comment]
最后解决的是，上传到后台，后台在上传到服务器。。
