### ISSUE TITLE
腾讯公司的特色：错误一律报一个，具体原因自己找，真TM坑啊

### ISSUE THREAD

**Issue by xdkaka** [tencentyun/cos-wx-sdk-v5#25]
云存储是报：403，没原因
微信支付是：缺少参数 total_fee

**Comment by carsonxu** [comment]
你好，COS CGI 很多错误返回，都有提示 Message 错误原因
你看到的 403 应该是返回 AccessDenied，是 sts 的凭证没权限，或者是密钥本身没权限。
如果定位不到，在这里贴一下 RequestId？

**Comment by xdkaka** [comment]
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied.</Message>
	<Resource>shoujike-img-1251612692.cos.ap-beijing.myqcloud.com/1.png</Resource>
	<RequestId>NWM4MDhmZDJfNzljMDBiMDlfMmRmYzBfMTM2OTNiZA==</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjMGU5NjQzNGY1N2ZkZTM2MmQ2NzI2NGU1ZGIyNDgxZDc=</TraceId>
</Error>

**Comment by xdkaka** [comment]
`<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied.</Message>
	<Resource>shoujike-img-1251612692.cos.ap-beijing.myqcloud.com/1.png</Resource>
	<RequestId>NWM4MDhmZDJfNzljMDBiMDlfMmRmYzBfMTM2OTNiZA==</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjMGU5NjQzNGY1N2ZkZTM2MmQ2NzI2NGU1ZGIyNDgxZDc=</TraceId>
</Error>

`

**Comment by xdkaka** [comment]
> <?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied.</Message>
	<Resource>shoujike-img-1251612692.cos.ap-beijing.myqcloud.com/1.png</Resource>
	<RequestId>NWM4MDhmZDJfNzljMDBiMDlfMmRmYzBfMTM2OTNiZA==</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjMGU5NjQzNGY1N2ZkZTM2MmQ2NzI2NGU1ZGIyNDgxZDc=</TraceId>
</Error>

**Comment by carsonxu** [comment]
STS policy 请求里补充一个 "name/cos:PostObject",

**Comment by carsonxu** [comment]
你用的是什么例子？我们到例子里也加上

**Comment by xdkaka** [comment]
有这个参数的name/cos:PostObject，用的就是官方的demo
````
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied.</Message>
	<Resource>shoujike-img-1251612692.cos.ap-beijing.myqcloud.com/1.png</Resource>
	<RequestId>NWM4MDhmZDJfNzljMDBiMDlfMmRmYzBfMTM2OTNiZA==</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjMGU5NjQzNGY1N2ZkZTM2MmQ2NzI2NGU1ZGIyNDgxZDc=</TraceId>
</Error>
````

````
$config = array(
                'url' => 'https://sts.api.qcloud.com/v2/index.php',
                'domain' => 'sts.api.qcloud.com',
                'proxy' => '',
                'secretId' => COS_KEY, // 固定密钥
                'secretKey' => COS_SECRET, // 固定密钥
                'bucket' => COS_BUCKET, // 换成你的 bucket
                'region' => COS_REGION, // 换成 bucket 所在园区
                'durationSeconds' => 1800, // 密钥有效期
                'allowPrefix' => '*', // 必填，这里改成允许的路径前缀，这里可以根据自己网站的用户登录态判断允许上传的目录，例子：* 或者 a/* 或者 a.jpg
                // 密钥的权限列表
                'allowActions' => array(
                    // 所有 action 请看文档 https://cloud.tencent.com/document/product/436/31923
                    // 简单上传
                    'name/cos:PutObject',
                    // 分片上传
                    'name/cos:InitiateMultipartUpload',
                    'name/cos:ListMultipartUploads',
                    'name/cos:ListParts',
                    'name/cos:UploadPart',
                    'name/cos:CompleteMultipartUpload',
                ),
            );
````
![image](https://user-images.githubusercontent.com/3340436/53931459-32baf800-40d0-11e9-83c3-4975c8b155ce.png)
![image](https://user-images.githubusercontent.com/3340436/53931463-351d5200-40d0-11e9-9e9d-9668275b367c.png)

**Comment by carsonxu** [comment]
有 'name/cos:PutObject'
没又 'name/cos:PostObject'
微信里上传只能 POST，导致只能 PostObject 上传

**Comment by xdkaka** [comment]
那麻烦官方文档后台PHP代码也加上吧，既然小程序不支持put，那把demo里demo-sdk.js这个SDK逻辑也去掉吧

**Comment by carsonxu** [comment]
ok

**Comment by xdkaka** [comment]
![image](https://user-images.githubusercontent.com/3340436/53931683-2e430f00-40d1-11e9-8001-fe8b624fdb60.png)
传成功了，但是显示0B。。。。

**Comment by carsonxu** [comment]
看了一遍，应该是使用了 https://github.com/tencentyun/cos-wx-sdk-v5/blob/master/server/sts.php 这个例子的 sts.php。考虑到后面可能还有用户这么使用，已补充 name/cos:PostObject 权限。
另外当前小程序 SDK 力 cos.putObject 接口还是有一些场景，比如写入文本到 COS 文件。所以例子需要保留有这个方法。

**Comment by ImReliefZk** [comment]
> 你好，COS CGI 很多错误返回，都有提示 Message 错误原因
> 你看到的 403 应该是返回 AccessDenied，是 sts 的凭证没权限，或者是密钥本身没权限。
> 如果定位不到，在这里贴一下 RequestId？

RequestId: "NWZlN2Y2MGJfNWM5ZDA4MDlfOTYwMl81ZDRiMzQ="
![image](https://user-images.githubusercontent.com/56526598/103162956-6e3d2e00-4832-11eb-992b-36c3753b8049.png)
