### ISSUE TITLE
按照官方demo传成功了，但是传上去大小为0B

### ISSUE THREAD

**Issue by xdkaka** [tencentyun/cos-wx-sdk-v5#26]
接上一个问题：https://github.com/tencentyun/cos-wx-sdk-v5/issues/25
按照demo传成功了，但是传上去大小为0B，这个有可能是什么原因，谢谢

**Comment by xdkaka** [comment]
腾讯云显示延时，过几秒就好了

**Comment by carsonxu** [comment]
ok
