### ISSUE TITLE
getAuthorization方法中获取的 Key是 空的

### ISSUE THREAD

**Issue by big-sponge** [tencentyun/cos-wx-sdk-v5#27]
![image](https://user-images.githubusercontent.com/19501267/54409056-b05db400-471f-11e9-8016-34704f2419c7.png)

![image](https://user-images.githubusercontent.com/19501267/54409067-bc497600-471f-11e9-8d20-7fa225d1eed5.png)

上面这个 key 是 空的 是不是 小程序 sdk 有bug

postObject方法中传递了 Key

但是 getAuthorization方法中获取的 Key是 空的

**Comment by carsonxu** [comment]
这里的 Key 是代表签名时，要签的 Pathname。字段会导致误解，已更改参数名为 Pathname。
其他接口文件名都是在 Url 里，postObject 接口是特殊的，文件名放在 Body，导致签名参数是 post /。
用 options.Pathname 就好了

**Comment by penweizgx** [comment]
> Pathname

这样怎么为上传的文件重命名和指定存放目录

**Comment by carsonxu** [comment]
PostObject 的 Key 是放在请求 Body 里发送的。form-data 格式。
如果是使用 SDK，指定 Key 参数即可：
```
cos.postObject({
    Bucket: config.Bucket,
    Region: config.Region,
    Key: '目录1/文件名1.png',
    FilePath: file.path,
    FileSize: file.size,
}, function (err, data) {
	console.log(err || data);
});
```
