### ISSUE TITLE
取不到上传后的回调

### ISSUE THREAD

**Issue by 583175694** [tencentyun/cos-wx-sdk-v5#28]
<img width="867" alt="WeChata75ba07bd1d4d722403f2390481536f1" src="https://user-images.githubusercontent.com/26473617/54592900-3ce1dc80-4a68-11e9-803d-763063de427a.png">
<img width="926" alt="WeChat4c493bc37360cb9e8ca1d5f680c8a695" src="https://user-images.githubusercontent.com/26473617/54592901-3ce1dc80-4a68-11e9-944d-9a2d77f0e85f.png">
图一使用es5的写法也不行，关键是有两个项目，一个项目可以取到回调，另一个项目无法取得回调，版本尝试过0.6.0与0.7.1，均无法取得回调

**Comment by carsonxu** [comment]
稳定复现吗？是否可以发代码看看？

**Comment by 583175694** [comment]
> 稳定复现吗？是否可以发代码看看？

稳定复现，直接在这里贴代码就好了吗？
`const cos = new COS({
      getAuthorization: function(params, callback) {
        const authorization = COS.getAuthorization({
          SecretId: config.SecretId,
          SecretKey: config.SecretKey,
          Method: params.Method,
          Key: params.Key
        })
        callback(authorization)
      }
    })

    cos.postObject({
      Bucket: config.Bucket,
      Region: config.Region,
      Key: Key,
      FilePath: currentMedia.mediaLocalPath,
      onProgress: async (info) => {
        console.log(info)
      }
    }, (err, data) => {
      console.log(err || data);
    })`

这些是关键代码，完整代码可能比较复杂，那些参数是没有问题的，媒体也能上传，就是没有回调，我目前的做法是判断进度那里的info.percent == 1 判断他上传完成

**Comment by 583175694** [comment]
> 稳定复现吗？是否可以发代码看看？

稳定复现，直接在这里贴代码就好了吗？
`const cos = new COS({
getAuthorization: function(params, callback) {
const authorization = COS.getAuthorization({
SecretId: config.SecretId,
SecretKey: config.SecretKey,
Method: params.Method,
Key: params.Key
})
callback(authorization)
}
})
cos.postObject({
  Bucket: config.Bucket,
  Region: config.Region,
  Key: Key,
  FilePath: currentMedia.mediaLocalPath,
  onProgress: async (info) => {
    console.log(info)
  }
}, (err, data) => {
  console.log(err || data);
})`
这些是关键代码，完整代码可能比较复杂，那些参数是没有问题的，媒体也能上传，就是没有回调，我目前的做法是判断进度那里的info.percent == 1 判断他上传完成

**Comment by 583175694** [comment]
> 稳定复现吗？是否可以发代码看看？

稳定复现，直接在这里贴代码就好了吗？

`const cos = new COS({
      getAuthorization: function(params, callback) {
        const authorization = COS.getAuthorization({
          SecretId: config.SecretId,
          SecretKey: config.SecretKey,
          Method: params.Method,
          Key: params.Key
        })
        callback(authorization)
      }
    })
    cos.postObject({
      Bucket: config.Bucket,
      Region: config.Region,
      Key: Key,
      FilePath: currentMedia.mediaLocalPath,
      onProgress: async (info) => {
        console.log(info)
      }
    }, (err, data) => {
      console.log(err || data);
    })`
这些是关键代码，完整代码可能比较复杂，那些参数是没有问题的，媒体也能上传，就是没有回调，我目前的做法是判断进度那里的info.percent == 1 判断他上传完成

**Comment by wkl007** [comment]
同样获取不到上传后的回调

**Comment by wkl007** [comment]
问题已解决，是taro编译的问题。在Taro编译时，忽略cos-wx-sdk-v5文件即可
```
compile: {
      compressTemplate: true,// 打包时是否需要压缩 wxml
      exclude: ['src/assets/js/cos-wx-sdk-v5.js']//添加代码
},
```

**Comment by Garfield550** [comment]
同样是 Taro，在这里记录一下，方便使用 Git 链接作为 package dependencies 的人解决问题。

```json
// package.json
"dependencies": {
  "cos-wx-sdk-v5": "https://github.com/tencentyun/cos-wx-sdk-v5.git#v0.7.2",
},
```

在引入 cos-wx-sdk-v5 时需要主动引入未经过编译的 index 文件，而不是 cos-wx-sdk-v5 在 package.json `main` 字段指定的 `cos-wx-sdk-v5/demo/cos-wx-sdk-v5.js` 文件，防止 Webpack 编译过的 cos-wx-sdk-v5.js 被 Taro 的 Babel 重新编译导致的回调失效问题。

```js
// YourApp.js
import COS from 'cos-wx-sdk-v5/index'; // 引入未经过编译的 index 文件 node_modules/cos-wx-sdk-v5/index.js
// import COS from 'cos-wx-sdk-v5'; // 这样写会引入 node_modules/cos-wx-sdk-v5/demo/cos-wx-sdk-v5.js 文件
```

这样就可以在回调中正常拿到状态码和图片地址了。

```js
{
  Location: "example.cos.ap-guangzhou.myqcloud.com/file-name.png"
  statusCode: 200
}
```

另外请注意，如果你的其他业务需要上传后的图片地址，不要忘记加 `https://` 前缀，可能会导致三方 Vender 程序崩溃（我的案例中）。

![image](https://user-images.githubusercontent.com/3471836/61686043-1eab2680-ad51-11e9-9cfb-e81cd95e8b60.png)
