### ISSUE TITLE
下载demo上传图片报错：TypeError: Cannot read property 'Authorization' of undefined

### ISSUE THREAD

**Issue by zhaobinglong** [tencentyun/cos-wx-sdk-v5#29]
该问题已解决：

原始demo：
![image](https://user-images.githubusercontent.com/8922614/55637621-0e018f80-57f8-11e9-9e9a-89f5075914a4.png)

修改后：
![image](https://user-images.githubusercontent.com/8922614/55637691-3c7f6a80-57f8-11e9-96db-1709a7765252.png)

请求签名回来的result.data是一个字符串，将它转为json对象，再获取里面的参数

**Comment by carsonxu** [comment]
指定 dataType: 'json' 就不用自行解析
