### ISSUE TITLE
getAuthorization 获取到的参数不对

### ISSUE THREAD

**Issue by xiedarin** [tencentyun/cos-wx-sdk-v5#3]
getAuthorization 获取到的参数是 {Method: "POST", Key: ""}
但我Key传的是文件名。

**Comment by carsonxu** [comment]
这个是正常的，postObject接口有点特殊的，Key放在body里面。签名用的是请求的路径 `/`。

**Comment by xiedarin** [comment]
知道了，里面有判断,method 是post的时候 不传key

**Comment by carsonxu** [comment]
ok

**Comment by carsonxu** [comment]
ok
