### ISSUE TITLE
403

### ISSUE THREAD

**Issue by MakerGYT** [tencentyun/cos-wx-sdk-v5#30]
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied.</Message>
	<ServerTime>2019-04-09T03:39:20Z</ServerTime>
	<Resource>wechat-12567014540.cos.ap-chengdu.myqcloud.com/wx3797508a5e86abc4.o6zAJswgmdYeKPMcMCHrceK2dEPg.XJUjCYfLQYu658775cd5728cea06330e944b2fa97b7b.jpg</Resource>
	<RequestId>NWNhYzEzZThfNGQ5ZTU4NjRfNmFhNV83YTZjOGY=</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjYjEzMGU3N2I0OTJjYTAwYWExNjJhODI1NTRkOGZlM2Y=</TraceId>
</Error>

**Comment by carsonxu** [comment]
现在解决了吗？这个请求太旧查不到信息。如果还需要支持可以在官网提交工单解决。
