### ISSUE TITLE
cos.postObject调用报Provisional headers are shown错误

### ISSUE THREAD

**Issue by Creat155** [tencentyun/cos-wx-sdk-v5#32]
cos-wx-sdk-v5已上传图片调用cos.postObject这个api报
![image](https://user-images.githubusercontent.com/39396448/59350036-aca4f200-8d4d-11e9-8bee-f1e060bfb9b3.png)

![image](https://user-images.githubusercontent.com/39396448/59350086-cfcfa180-8d4d-11e9-9d4f-1427ed2cd46c.png)

**Comment by carsonxu** [comment]
这个应该不影响上传的正常使用？
