### ISSUE TITLE
小程序SDK能支持分片上传吗

### ISSUE THREAD

**Issue by XJingWei** [tencentyun/cos-wx-sdk-v5#35]
最近碰到项目需要上传图片、视频文件比较大，希望能提供分片上传

**Comment by carsonxu** [comment]
暂不支持，近期尝试微信接口，如果可以实现会加上。

**Comment by carsonxu** [comment]
调研过接口还不能满足分片需要，没有指定开始结束位置读取文件内容的接口。
等微信支持接口后，再支持分片上传。

**Comment by carsonxu** [comment]
已支持分片上传。v1.0.3
