### ISSUE TITLE
安卓小程序中上传文件返回上传百分比有问题

### ISSUE THREAD

**Issue by XJingWei** [tencentyun/cos-wx-sdk-v5#36]
安卓手机上传文件返回已上传百分比不正确。
在IOS、小程序开发者工具中没有问题，只有安卓出现！
![image](https://user-images.githubusercontent.com/41570023/67205872-39ba2f00-f443-11e9-9364-adcde519c671.png)

**Comment by XJingWei** [comment]
在安卓中只会返回一次进度直接100%，和网路、文件大小无关已验证

**Comment by carsonxu** [comment]
现在是否还会？
应该是部分低版本手机，微信接口进度没反馈导致。
如果不行可以使用 sliceUploadFile 分片上传接口。
