### ISSUE TITLE
PostObject 方法能否支持cos的cname地址

### ISSUE THREAD

**Issue by HoloShadow** [tencentyun/cos-wx-sdk-v5#37]
如题

**Comment by HoloShadow** [comment]
即支持自定义域名

**Comment by carsonxu** [comment]
1. 支持的，实例化时，传入 Domain 参数，格式看文档
2. 你需求应该是有多个存储桶，不想每个都配置域名白名单，可以考虑用后缀式请求 ForcePathStyle: true
https://cloud.tencent.com/document/product/436/31953#.E5.88.9D.E5.A7.8B.E5.8C.96
