### ISSUE TITLE
图片上传成功，但是有错误提示

### ISSUE THREAD

**Issue by nevertback** [tencentyun/cos-wx-sdk-v5#39]
![未命名1598516230](https://user-images.githubusercontent.com/4335773/91415982-5a33f080-e881-11ea-9656-433494f68c05.png)
错误信息：
VM80:1 [xmldom error]	invalid doc source 
@#[line:0,col:undefined]

**Comment by carsonxu** [comment]
可以提供最小复现代码吗？

**Comment by nevertback** [comment]
```javascript
export function uploadToCos(tmpPath) {
	return new Promise((resolve, reject) => {
		const fileName = filePath.substr(filePath.lastIndexOf('/') + 1);
		const cos = new COS({
			getAuthorization: function(options, callback) {
				wx.request({
					method: 'GET',
					url: '***',
					success: function(result) {
						const data = result.data;
						const credentials = data && data.credentials;
						if (!data || !credentials) return console.error('credentials invalid')
						callback({
							TmpSecretId: credentials.tmpSecretId,
							TmpSecretKey: credentials.tmpSecretKey,
							XCosSecurityToken: credentials.sessionToken,
							StartTime: data.startTime,
							ExpiredTime: data.expiredTime
						});
					}
				});
			}
		})
		cos.postObject({
			Bucket: '***',
			Region: '***',
			Key: filename,
			FilePath: tmpPath,
			onProgress: function(info) {
				// console.log(info)
			},
		}, function(err, data) {
			if (err) {
				reject(err)
			} else {				
				resolve(data.Location)
			}
		})
	})
}
```

**Comment by webfunction** [comment]
> ```js
> export function uploadToCos(tmpPath) {
> 	return new Promise((resolve, reject) => {
> 		const fileName = filePath.substr(filePath.lastIndexOf('/') + 1);
> 		const cos = new COS({
> 			getAuthorization: function(options, callback) {
> 				wx.request({
> 					method: 'GET',
> 					url: '***',
> 					success: function(result) {
> 						const data = result.data;
> 						const credentials = data && data.credentials;
> 						if (!data || !credentials) return console.error('credentials invalid')
> 						callback({
> 							TmpSecretId: credentials.tmpSecretId,
> 							TmpSecretKey: credentials.tmpSecretKey,
> 							XCosSecurityToken: credentials.sessionToken,
> 							StartTime: data.startTime,
> 							ExpiredTime: data.expiredTime
> 						});
> 					}
> 				});
> 			}
> 		})
> 		cos.postObject({
> 			Bucket: '***',
> 			Region: '***',
> 			Key: filename,
> 			FilePath: tmpPath,
> 			onProgress: function(info) {
> 				// console.log(info)
> 			},
> 		}, function(err, data) {
> 			if (err) {
> 				reject(err)
> 			} else {				
> 				resolve(data.Location)
> 			}
> 		})
> 	})
> }
> ```
同样的问题

**Comment by lihaiJett** [comment]
同样错误提示，之前的版本没问题，换了最新的sdk后出现

**Comment by Sabirjan** [comment]
同样问题invalid doc source

**Comment by Sabirjan** [comment]
Uni-app

**Comment by Sabirjan** [comment]
@carsonxu

**Comment by carsonxu** [comment]
@Sabirjan 小程序是哪个平台，什么版本？最近测试过，没复现。
目前看是可以忽略的错误，由于 Response Header 有 Content-Type: application/xml ，且返回的 Body 空。
小程序会去以 xml 格式解析这个 Body 导致报错。

**Comment by Sabirjan** [comment]
@carsonxu 下载官方的SDK文件有问题，下载github的没问题了

**Comment by carsonxu** [comment]
感谢反馈，已更新下载地址，后续会保持最新。
