### ISSUE TITLE
返回结果的Location与实际的对象地址不一致

### ISSUE THREAD

**Issue by lihaiJett** [tencentyun/cos-wx-sdk-v5#43]
调用postObject上传文件，如果文件名带有特殊符号，例如等号“=”。
在返回的Location中，“=”会变成"%3D"；
但是在腾讯云控制台可以看到，实际的地址中，“=”是变成了“%253D”。

从调试器看到，之前的版本post请求是直接发"="的，现在的版本发的是编码后的“%3D”。明显sdk多做了一个步骤。

**Comment by Hxmic** [comment]
上传 403  咋回事

**Comment by carsonxu** [comment]
@Hxmic 提供下 RequestId。

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/105972677-d77cbf00-60c6-11eb-8279-5b402a9c6b67.png)


我只只上传单文件的。然后 就直接 403

**Comment by Hxmic** [comment]
有没有什么我自己测试的方法

**Comment by carsonxu** [comment]
参考这个 demo：
https://github.com/tencentyun/cos-wx-sdk-v5/blob/master/demo/demo-no-sdk.js

**Comment by Hxmic** [comment]
我就是和这个写的一样的。

**Comment by carsonxu** [comment]
403 应该是以下几种情况：

**Comment by Hxmic** [comment]
只改了， 从服务端获取 credentials   （放在Python 可以正常使用。）
然后  通过 CosAuth  获取签名。  
最后 走到 success了，但是没有上传成功。

**Comment by carsonxu** [comment]
403 应该是以下几种情况：
1. 签名和请求对不上，PostObject 请求的签名参数是 POST /
2. 临时密钥的 policy 缺权限，比如缺 action PostObject，比如 resource 没包含上传文件
3. 固定密钥本身身份没有权限
看看自行排查下，如果排查不出来，可以提工单贴上 RequestId。

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/105974067-7524be00-60c8-11eb-803e-6e06e2f9fff8.png)

这块我们看了下，没啥问题呀。 resource，应该是资源文件吧。这块都是包含的。


怎么提工单。

**Comment by carsonxu** [comment]
https://cloud.tencent.com/online-service

**Comment by Hxmic** [comment]
![image](https://user-images.githubusercontent.com/23522154/105985485-79f06e80-60d6-11eb-83df-acc8cc3f0073.png)
什么意思 呢 ？



Connection: "keep-alive"
Content-Length: "563"
Content-Type: "application/xml"
Date: "Wed, 27 Jan 2021 11:32:38 GMT"
Server: "tencent-cos"
x-cos-request-id: "NjAxMTRmNTZfNzVjODJhMDlfMzBjNGRfMzQ5NDFkNw=="
x-cos-trace-id: "OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjYjQ4YWNmNTExZDQwYWNmODY3OGE1ODU3ZDQzMDUzM2I="

**Comment by Hxmic** [comment]
获取到 加密参数 和  uploadFile 中的formData 中的key 不一致导致的。

**Comment by Hxmic** [comment]
获取到 加密参数 和  uploadFile 中的formData 中的key 不一致导致的。

**Comment by carsonxu** [comment]
> 调用postObject上传文件，如果文件名带有特殊符号，例如等号“=”。
> 在返回的Location中，“=”会变成"%3D"；
> 但是在腾讯云控制台可以看到，实际的地址中，“=”是变成了“%253D”。
> 
> 从调试器看到，之前的版本post请求是直接发"="的，现在的版本发的是编码后的“%3D”。明显sdk多做了一个步骤。

这个验证过，没有问题的。上传的 Key 是 '=' 返回的 Location 是：
