### ISSUE TITLE
是 options.Key和options.Method吗？

### ISSUE THREAD

**Issue by maxdu** [tencentyun/cos-wx-sdk-v5#5]
// 初始化实例
var cos = new COS({
    getAuthorization: function (**_options_**, callback) {
        // 异步获取签名
        wx.request({
            url: 'https://example.com/sign', // 步骤二提供的签名接口
            data: {
                Method: _**params**_.Method,
                Key: _**params**_.Key
            },
            dataType: 'text',
            success: function (result) {
                callback(result.data);
            }
        });
    }
});

**Comment by carsonxu** [comment]
已更正，谢谢
