### ISSUE TITLE
Pic-Operations 是否在postobject 可以被支持

### ISSUE THREAD

**Issue by social-uni** [tencentyun/cos-wx-sdk-v5#51]
copy #38 https://github.com/tencentyun/cos-wx-sdk-v5/issues/38

文档里没有看到可以在上传图片的时候如何做持久化操作，请问是否sdk支持使用postobject上传图片的时候对文件做持久化处理，感谢！

用的是sdk, 看了下代码，postobject 没有处理持久化操作的 “Pic-Operations” header，新版本可以考虑添加么，因为想在上传图片的时候，使用数据万象操作图片比如缩略等等，感谢您的回复

postobject方法中有一段过滤headers的代码，感觉是不支持的吧
```
for (var key in params) {
        if (key.indexOf('x-cos-meta-') > -1) {
            headers[key] = params[key];
        }
    }
```

以下为postobject方法代码
```
function postObject(params, callback) {
    var self = this;
    var headers = {};
    var filePath = params.FilePath;
    if (!filePath) {
        callback({error: 'missing param FilePath'});
        return;
    }

    headers['Cache-Control'] = params['CacheControl'];
    headers['Content-Disposition'] = params['ContentDisposition'];
    headers['Content-Encoding'] = params['ContentEncoding'];
    headers['Content-MD5'] = params['ContentMD5'];
    headers['Content-Length'] = params['ContentLength'];
    headers['Content-Type'] = params['ContentType'];
    headers['Expect'] = params['Expect'];
    headers['Expires'] = params['Expires'];
    headers['x-cos-acl'] = params['ACL'];
    headers['x-cos-grant-read'] = params['GrantRead'];
    headers['x-cos-grant-write'] = params['GrantWrite'];
    headers['x-cos-grant-full-control'] = params['GrantFullControl'];
    headers['x-cos-storage-class'] = params['StorageClass'];

    // 删除 Content-Length 避免签名错误
    delete headers['Content-Length'];
    delete headers['content-length'];

    for (var key in params) {
        if (key.indexOf('x-cos-meta-') > -1) {
            headers[key] = params[key];
        }
    }

    var onProgress = util.throttleOnProgress.call(self, headers['Content-Length'], params.onProgress);

    submitRequest.call(this, {
        Action: 'name/cos:PostObject',
        method: 'POST',
        Bucket: params.Bucket,
        Region: params.Region,
        Key: params.Key,
        headers: headers,
        qs: params.Query,
        filePath: filePath,
        onProgress: onProgress,
    }, function (err, data) {
        onProgress(null, true);
        if (err) return callback(err);
        if (data && data.headers) {
            var headers = data.headers;
            var ETag = headers.etag || headers.Etag || headers.ETag || '';
            var filename = filePath.substr(filePath.lastIndexOf('/') + 1);
            var url = getUrl({
                ForcePathStyle: self.options.ForcePathStyle,
                protocol: self.options.Protocol,
                domain: self.options.Domain,
                bucket: params.Bucket,
                region: params.Region,
                object: params.Key.replace(/\$\{filename\}/g, filename),
                isLocation: true,
            });

            return callback(null, {
                Location: url,
                statusCode: data.statusCode,
                headers: headers,
                ETag: ETag,
            });
        }
        callback(null, data);
    });
}
```

**Comment by livehigh** [comment]
> copy #38 #38
> 
> 文档里没有看到可以在上传图片的时候如何做持久化操作，请问是否sdk支持使用postobject上传图片的时候对文件做持久化处理，感谢！
> 
> 用的是sdk, 看了下代码，postobject 没有处理持久化操作的 “Pic-Operations” header，新版本可以考虑添加么，因为想在上传图片的时候，使用数据万象操作图片比如缩略等等，感谢您的回复
> 
> postobject方法中有一段过滤headers的代码，感觉是不支持的吧
> 
> ```
> for (var key in params) {
>         if (key.indexOf('x-cos-meta-') > -1) {
>             headers[key] = params[key];
>         }
>     }
> ```
> 
> 以下为postobject方法代码
> 
> ```
> function postObject(params, callback) {
>     var self = this;
>     var headers = {};
>     var filePath = params.FilePath;
>     if (!filePath) {
>         callback({error: 'missing param FilePath'});
>         return;
>     }
> 
>     headers['Cache-Control'] = params['CacheControl'];
>     headers['Content-Disposition'] = params['ContentDisposition'];
>     headers['Content-Encoding'] = params['ContentEncoding'];
>     headers['Content-MD5'] = params['ContentMD5'];
>     headers['Content-Length'] = params['ContentLength'];
>     headers['Content-Type'] = params['ContentType'];
>     headers['Expect'] = params['Expect'];
>     headers['Expires'] = params['Expires'];
>     headers['x-cos-acl'] = params['ACL'];
>     headers['x-cos-grant-read'] = params['GrantRead'];
>     headers['x-cos-grant-write'] = params['GrantWrite'];
>     headers['x-cos-grant-full-control'] = params['GrantFullControl'];
>     headers['x-cos-storage-class'] = params['StorageClass'];
> 
>     // 删除 Content-Length 避免签名错误
>     delete headers['Content-Length'];
>     delete headers['content-length'];
> 
>     for (var key in params) {
>         if (key.indexOf('x-cos-meta-') > -1) {
>             headers[key] = params[key];
>         }
>     }
> 
>     var onProgress = util.throttleOnProgress.call(self, headers['Content-Length'], params.onProgress);
> 
>     submitRequest.call(this, {
>         Action: 'name/cos:PostObject',
>         method: 'POST',
>         Bucket: params.Bucket,
>         Region: params.Region,
>         Key: params.Key,
>         headers: headers,
>         qs: params.Query,
>         filePath: filePath,
>         onProgress: onProgress,
>     }, function (err, data) {
>         onProgress(null, true);
>         if (err) return callback(err);
>         if (data && data.headers) {
>             var headers = data.headers;
>             var ETag = headers.etag || headers.Etag || headers.ETag || '';
>             var filename = filePath.substr(filePath.lastIndexOf('/') + 1);
>             var url = getUrl({
>                 ForcePathStyle: self.options.ForcePathStyle,
>                 protocol: self.options.Protocol,
>                 domain: self.options.Domain,
>                 bucket: params.Bucket,
>                 region: params.Region,
>                 object: params.Key.replace(/\$\{filename\}/g, filename),
>                 isLocation: true,
>             });
> 
>             return callback(null, {
>                 Location: url,
>                 statusCode: data.statusCode,
>                 headers: headers,
>                 ETag: ETag,
>             });
>         }
>         callback(null, data);
>     });
> }
> ```

postObject不支持，可以用putObject

**Comment by Yurunsoft** [comment]
@livehigh 小程序并不支持putObject，为何不在postObject里支持？

**Comment by livehigh** [comment]
> 

你好，小程序是支持putObject的

**Comment by livehigh** [comment]
> @livehigh 小程序并不支持putObject，为何不在postObject里支持？

你好，小程序是支持putObject的

**Comment by Yurunsoft** [comment]
putObject 提示AccessDenied

**Comment by livehigh** [comment]
> putObject 提示AccessDenied

一般是权限不足导致的，麻烦提供下requestId

**Comment by Yurunsoft** [comment]
requestId:`NjI4NDUxZjNfNjA5ZDA4MDlfYjdhOV9iZDAxYmE=`

**Comment by livehigh** [comment]
> requestId:`NjI4NDUxZjNfNjA5ZDA4MDlfYjdhOV9iZDAxYmE=`

这边从发过来的请求看是图片损坏了，你也可以进群咨询哈，方便回复。
群里发下原图和使用的代码我看看下。

https://console.cloud.tencent.com/cos

![image](https://user-images.githubusercontent.com/25949099/168948204-71eaaab1-5d52-471d-a3a4-69de1827cad8.png)

**Comment by Yurunsoft** [comment]
谢谢，刚刚问题解决了，是我们前端编写问题。。

**Comment by livehigh** [comment]
> 谢谢，刚刚问题解决了，是我们前端编写问题。。

好的
