### ISSUE TITLE
加了压缩版本麻烦发个版本呀

### ISSUE THREAD

**Issue by NuoHui** [tencentyun/cos-wx-sdk-v5#59]

**Comment by livehigh** [comment]
> 

您好，最新版本V1.1.2已经发布，请下载使用

**Comment by NuoHui** [comment]
@livehigh `"main": "demo/lib/cos-wx-sdk-v5.js",` 1.1.2。不是指向压缩版本的哈，发个新的预计什么时候呢

**Comment by livehigh** [comment]
> @livehigh `"main": "demo/lib/cos-wx-sdk-v5.js",` 1.1.2。不是指向压缩版本的哈，发个新的预计什么时候呢

感谢反馈，刚刚发布了v1.1.3，从这个版本开始我们默认的入口文件改为压缩版。
