### ISSUE TITLE
putObject

### ISSUE THREAD

**Issue by kknono** [tencentyun/cos-wx-sdk-v5#8]
有putObject的demo吗

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-wx-sdk-v5/blob/master/demo/demo.js#L149-L156

**Comment by kknono** [comment]
cos+语音自动识别。我们测试下来以及反馈给腾讯云工程师。  用这个sdk直接post提交，无法进行自动的智能语音识别的。

**Comment by carsonxu** [comment]
看这里是没办法直接传，这里语音文件较小，可否找个中专的服务器？

**Comment by carsonxu** [comment]
这个问题已在最新版本修复，两周内会全量完成

**Comment by kknono** [comment]
你好，目前这个版本可以使用了吗?

**Comment by kknono** [comment]
也就是在微信端直接postobject到cos，然后cos可以通过语音自动识别出来。否则需要通过中转，各种开销比较大。

**Comment by carsonxu** [comment]
上周已全量

**Comment by kknono** [comment]
给力。  C端的lib不需要更新吧。

**Comment by carsonxu** [comment]
不需要的

**Comment by carsonxu** [comment]
这个错误是请求太频繁，试试再次请求

**Comment by kknono** [comment]
你好。当从小程序端利用sdk上传到cos，可以成功。但是目前还是无法自动进行语音识别。异步回来的日志显示，audioUrl明显不对。 缺乏具体的文件名。 (  audioUrl: 'http://xxxxx.cos.ap-shanghai.myqcloud.com/',
)


但是在控制台上传相同的mp3文件，可以自动进行语音识别。

**Comment by carsonxu** [comment]
@runzx 试试最新 github 代码

**Comment by kknono** [comment]
Code
:
"InvalidArgument"
Message
:
"x-cos-acl value invalid:[object Undefined]"

换了最新版本也是同样的问题。
