### ISSUE TITLE
微信小程序wx.chooseMedia如何使用

### ISSUE THREAD

**Issue by shaomingming008** [tencentyun/cos-wx-sdk-v5#86]
之前的chooseImage chooseVideo都可以  但是这两个不维护了  现在用chooseMedia  但是传给VodUploader.start()里面就直接报错

**Comment by livehigh** [comment]
> VodUploader.start()

需要看看VodUploader.start()需要接收的参数哈  chooseVideo和chooseMedia返回的数据格式不同
