### ISSUE TITLE
使用临时密钥初始化后上传失败

### ISSUE THREAD

**Issue by YokongHe** [tencentyun/cos-wx-sdk-v5#9]
后台使用的javaSDK生成的临时密钥，在上传文件的时候报"AccessDenied"

**Comment by carsonxu** [comment]
临时密钥里面的 Policy 发一下，需要把 PutObject 和 PostObject 权限加上

**Comment by YokongHe** [comment]
更换了，还是AccessDenied，我还参考了js SDK中的方法
 callback({
          SecretId: result.data.data.credentials.tmpSecretId,
          SecretKey: result.data.data.credentials.tmpSecretKey,
          SessionToken: result.data.data.credentials.sessionToken,
          ExpiredTime: result.data.data.expiredTime,
        })
也还是不行

**Comment by carsonxu** [comment]
临时密钥用法，参考当前 demo 以及 server/sts.php
