### ISSUE TITLE
代码中使用了eval

### ISSUE THREAD

**Issue by xietiansheng** [tencentyun/cos-wx-sdk-v5#95]
​node_modules/cos-wx-sdk-v5/demo/lib/cos-wx-sdk-v5.min.js (1:60650) Use of eval in "node_modules/cos-wx-sdk-v5/demo/lib/cos-wx-sdk-v5.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.

**Comment by livehigh** [comment]
感谢反馈  下个版本我们将优化这里

**Comment by livehigh** [comment]
fixed
